# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js blog to Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout test
        run: cd /var/www/Blog_Nextjs14 && sudo git fetch --all && sudo git reset hard origin/main && sudo git pull origin main
      - name: run
        run: cd /var/www/Blog_Nextjs14 && sudo yarn install && sudo yarn build

