# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js blog to Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Dependencies
        run: yarn install
      - name: Build NextJS in Yarn
        run: yarn build
  
